import{describe,it,expect}from"vitest";import{evaluateRules}from"@/lib/services/ruleEngine";import{calculateScore}from"@/lib/services/riskScoring";import{projectFix}from"@/lib/services/fixSimulator";
import{RULE_CATALOG,SCORING_RATIONALE}from"@/lib/ruleCatalog";
import validationCases from "./fixtures/independent-validation-cases.json";
const now=new Date("2026-01-01"),future=new Date("2027-01-01"),past=new Date("2025-01-01");const base={dataRetentionEndDate:future,transparencyNoticeGiven:true,dataMinimizationStatus:"compliant",consentRecords:[{status:"active",expiresAt:future}],processingPurposes:[{active:true,lawfulBasis:"Consent"}]};
describe("rule engine",()=>{it("passes all five for a valid contact",()=>expect(evaluateRules(base,now).every(x=>x.passed)).toBe(true));it.each([
 ["DPDP-001",{consentRecords:[]}],["DPDP-002",{processingPurposes:[]}],["DPDP-003",{dataRetentionEndDate:past}],["DPDP-004",{transparencyNoticeGiven:false}],["DPDP-005",{dataMinimizationStatus:"non_compliant"}]
])("fails only %s for its scenario",(code,change)=>{const r=evaluateRules({...base,...change},now);expect(r.filter(x=>!x.passed).map(x=>x.ruleCode)).toEqual([code])});it("rejects expired and withdrawn consent",()=>{expect(evaluateRules({...base,consentRecords:[{status:"active",expiresAt:past}]},now)[0].passed).toBe(false);expect(evaluateRules({...base,consentRecords:[{status:"withdrawn",expiresAt:future}]},now)[0].passed).toBe(false)})});
describe("six personas",()=>{it.each([
 ["Aisha",{},100,"Compliant"],["Rahul",{consentRecords:[]},70,"At Risk"],["Priya",{dataRetentionEndDate:past},80,"At Risk"],["Arjun",{consentRecords:[],dataRetentionEndDate:past,dataMinimizationStatus:"non_compliant"},35,"Non-Compliant"],["Neha",{processingPurposes:[]},80,"At Risk"],["Imran",{transparencyNoticeGiven:false},85,"Compliant"]
])("scores %s deterministically",(_,change,score,status)=>expect(calculateScore(evaluateRules({...base,...change},now))).toEqual({score,status}))});
describe("risk scoring and simulator",()=>{it("floors a score at zero",()=>expect(calculateScore([...evaluateRules({...base,consentRecords:[],processingPurposes:[],dataRetentionEndDate:past,transparencyNoticeGiven:false,dataMinimizationStatus:"non_compliant"},now),{...evaluateRules(base,now)[0],passed:false,deduction:50}]).score).toBe(0));it("gates a high-severity score at At Risk until all high/critical findings are fixed",()=>{const results=evaluateRules({...base,consentRecords:[],dataRetentionEndDate:past},now);expect(projectFix(50,results,["DPDP-001"])).toEqual({currentScore:50,projectedScore:80,delta:30,projectedStatus:"At Risk"});expect(results[0].passed).toBe(false)});it("does not mark a critical finding compliant at 70",()=>expect(calculateScore(evaluateRules({...base,consentRecords:[]},now)).status).toBe("At Risk"))});
describe("legal traceability",()=>{it("provides a legal mapping and field-level method for every rule",()=>{for(const rule of Object.values(RULE_CATALOG)){expect(rule.legalReference.length).toBeGreaterThan(5);expect(rule.legalRequirement.length).toBeGreaterThan(30);expect(rule.testMethod.length).toBeGreaterThan(30)}});it("marks the minimization control as an operational proxy",()=>expect(RULE_CATALOG["DPDP-005"].mappingType).toBe("operational_proxy"));it("labels the scoring model as a heuristic",()=>expect(SCORING_RATIONALE.model).toContain("heuristic"))});
describe("independent labelled acceptance dataset",()=>{it("matches all 30 review cases",()=>{const template=evaluateRules(base,now);expect(validationCases).toHaveLength(30);for(const item of validationCases){const results=template.map(r=>({...r,passed:!item.failures.includes(r.ruleCode)}));expect(calculateScore(results)).toEqual({score:item.score,status:item.status});}})});
