"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,XCircle,Play,ShieldAlert} from "lucide-react";
type Result={ruleCode:string;passed:boolean;detail:string};type Rec={ruleCode:string;action:string;expectedScoreImprovement:number;priority:number};type Remediation={id:string;ruleCode:string;type:string;status:string;draftContent:string};type Assessment={id:string;riskScore:number;status:string;violationCount:number;assessedAt:string;results:Result[];recommendations:Rec[]};type Contact={id:string;name:string;email:string;department?:string;assessments:Assessment[];remediationRequests:Remediation[]};
const title:Record<string,string>={"DPDP-001":"Consent validation","DPDP-002":"Purpose validation","DPDP-003":"Retention validation","DPDP-004":"Transparency notice","DPDP-005":"Data minimization"};
export default function ContactDetailClient({id}:{id:string}){
 const[data,setData]=useState<Contact>(),[tab,setTab]=useState("assessment"),[busy,setBusy]=useState(false);const load=()=>fetch(`/api/contacts/${id}`).then(r=>r.json()).then(setData);useEffect(()=>{load()},[id]);const a=data?.assessments[0],failed=a?.results.filter(r=>!r.passed)||[];
 async function assess(){setBusy(true);await fetch("/api/assessments/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contactId:id})});await load();setBusy(false)}
 async function draft(){setBusy(true);await fetch("/api/remediations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contactIds:[id],type:"consent_renewal"})});await load();setBusy(false)}
 async function act(remediationId:string,action:"approve"|"reject"|"apply"){setBusy(true);await fetch(`/api/remediations/${remediationId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})});await load();setBusy(false)}
 if(!data)return <p>Loading contact…</p>;
 return <><Link href="/dashboard" className="text-sm text-slate-500 flex gap-2 items-center mb-5"><ArrowLeft size={15}/>Back to overview</Link><div className="flex flex-col md:flex-row gap-4 justify-between md:items-end mb-6"><div><div className="flex gap-3 items-center"><h1 className="text-3xl font-bold text-[#10233f]">{data.name}</h1>{a&&<span className={`badge ${a.status==="Compliant"?"good":a.status==="At Risk"?"warn":"bad"}`}>{a.status}</span>}</div><p className="text-slate-500 mt-2">{data.email} · {data.department||"Unassigned"}</p></div><button onClick={assess} disabled={busy} className="btn btn-primary flex gap-2 items-center"><Play size={16}/>{busy?"Working…":"Run new assessment"}</button></div>
 {!a?<div className="card p-10 text-center"><ShieldAlert className="mx-auto text-slate-400"/><h2 className="font-bold mt-4">No assessment yet</h2></div>:<><div className="grid sm:grid-cols-3 gap-4 mb-6"><div className="card p-5"><p className="label">Risk score</p><p className="text-4xl font-bold mt-2">{a.riskScore}<span className="text-base text-slate-400">/100</span></p></div><div className="card p-5"><p className="label">Rules passed</p><p className="text-4xl font-bold mt-2 text-emerald-600">{5-a.violationCount}<span className="text-base text-slate-400">/5</span></p></div><div className="card p-5"><p className="label">Decision guard</p><p className="font-bold mt-3 text-slate-700">Open High/Critical findings cannot be Compliant</p></div></div><div className="flex gap-1 border-b border-slate-300 mb-6 overflow-x-auto">{[["assessment","Assessment"],["remediate","Remediation"],["advisor","Readiness advisor"]].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`px-4 py-3 text-sm whitespace-nowrap border-b-2 ${tab===v?"border-teal-600 text-teal-700 font-bold":"border-transparent text-slate-500"}`}>{l}</button>)}</div>
 {tab==="assessment"&&<div className="card p-5"><h2 className="font-bold text-lg mb-4">Rule-by-rule evidence</h2><div className="space-y-3">{a.results.map(r=><div key={r.ruleCode} className={`border rounded-xl p-4 flex gap-3 ${r.passed?"border-emerald-200 bg-emerald-50/40":"border-red-200 bg-red-50/40"}`}>{r.passed?<CheckCircle2 className="text-emerald-600 shrink-0"/>:<XCircle className="text-red-600 shrink-0"/>}<div><b>{r.ruleCode} · {title[r.ruleCode]}</b><p className="text-sm text-slate-600 mt-1">{r.detail}</p></div></div>)}</div></div>}
 {tab==="remediate"&&<div className="card p-5"><div className="flex flex-col sm:flex-row gap-3 justify-between sm:items-start"><div><h2 className="font-bold text-lg">Consent renewal workflow</h2><p className="text-sm text-slate-500 mt-1">Draft → human approval → mark action applied. The system never sends a request automatically.</p></div><button disabled={busy||!failed.some(r=>r.ruleCode==="DPDP-001")} onClick={draft} className="btn btn-primary">Draft consent renewal</button></div><div className="mt-5 space-y-4">{data.remediationRequests.length?data.remediationRequests.map(r=><div key={r.id} className="border rounded-xl p-4"><div className="flex justify-between gap-3"><b>{r.ruleCode} · {r.type.replaceAll("_"," ")}</b><span className={`badge ${r.status==="approved"||r.status==="applied"?"good":r.status==="rejected"?"bad":"warn"}`}>{r.status.replaceAll("_"," ")}</span></div><pre className="mt-3 whitespace-pre-wrap text-sm text-slate-600 font-sans bg-slate-50 p-3 rounded-lg">{r.draftContent}</pre>{r.status==="pending_approval"&&<div className="mt-3 flex gap-2"><button className="btn btn-primary text-sm" disabled={busy} onClick={()=>act(r.id,"approve")}>Approve</button><button className="btn btn-secondary text-sm" disabled={busy} onClick={()=>act(r.id,"reject")}>Reject</button></div>}{r.status==="approved"&&<button className="btn btn-primary text-sm mt-3" disabled={busy} onClick={()=>act(r.id,"apply")}>Mark approved action applied</button>}</div>):<p className="text-slate-500 text-sm">No draft yet. A consent-renewal draft is available only when DPDP-001 is open.</p>}</div></div>}
 {tab==="advisor"&&<div className="card p-5"><h2 className="font-bold text-lg">Prioritized remediation plan</h2>{a.recommendations.map(x=><div className="flex gap-4 p-4 border-b last:border-0" key={x.ruleCode}><span className="w-8 h-8 shrink-0 rounded-full bg-[#102747] text-white grid place-items-center font-bold">{x.priority}</span><div className="grow"><b>{x.action}</b><p className="text-sm text-slate-500 mt-1">Resolves {x.ruleCode}</p></div><span className="badge good self-start">+{x.expectedScoreImprovement}</span></div>)}</div>}</>}</>;
}
